### ISSUE TITLE
Can you provide some documentation on what the set_billing_period command?

### ISSUE THREAD

**Issue by gururise** [rainforestautomation/Emu-Serial-API#1]
There is no documentation on what the set_billing_period command does or how it functions.  I am trying to allow my EMU2 to work with SCE TOU rates and have a python program that sets the price depending on the time of day.  I'm wondering if the set_billing_period command was meant for TOU rates; unfortunately, there is no documentation on this command.  I would like the lights to turn on based upon whether I am currently in the super off-peak, off-peak, or on-peak rate.

**Comment by J-L** [comment]
Hey guru, The form of the command set_billing_period not meant for TOU rates -but sets beginning and end of the bill (if not provided by utility).The XML command looks like this, but should only work if the utility has not set up the period:

```
<Command>
  <Name>set_billing_period</Name>
  <Period>0x01</Period>
  <Start>0x1afc003c</Start>
  <Duration>0x0000002000</Duration>
</Command>
```

There currently is no way to set the LED lights though serial and it is only triggered by the internal demand values.

I'll put in an internal feature request for the next revision of firmware, but in the near term there will be no way to do this.

As we're pretty new to posting code to Github, thanks for our first issue!

**Comment by gururise** [comment]
Hi J-L, 

Just checking in to see if you were able to get the feature of setting the LED lights through serial into the firmware?  Would be great to be able to set the lights manually.

Thanks!

**Comment by J-L** [comment]
Hey Guru, 

I put in an feature request into our internal ticket, but feedback from the team has indicated this is not a feature which will be implemented.

Thanks for your input,
John
